branch-defaults:
  master:
    environment: webapi-dev
global:
  application_name: tasklist
  default_ec2_keyname: general
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1
  default_region: ap-northeast-1
  profile: null
  sc: git
deploy:
  artifact: target/eb/artifact.zip
